### ISSUE TITLE
Test with Atomics.waitAsync()

### ISSUE THREAD

**Issue by guest271314** [chcunningham/atomics-post-message#1]
Using `Atomics.waitAsync()` https://v8.dev/features/atomics achieves the expected result

```
async function sendPostMessageAndWait() {
  console.log('worker A: sending postMessage to B');
  workerB.postMessage('hello from A');

  console.log('worker A: starting wait() (waits forever)');
  const sab = new SharedArrayBuffer(1024);
  const int32 = new Int32Array(sab);
  const {async:result} = Atomics.waitAsync(int32, 0, 0);
  console.log(result instanceof Promise ? await result.value : result);
  
}
```

**Comment by chcunningham** [comment]
That's good to know. In my case I require the blocking version (due to requirements from a third party wasm lib).

**Comment by guest271314** [comment]
It appears `Atomics.waitAsync()` was designed specifically for this use case. If a prospective change in Chrome occurs for `wait()` for this report, won't that effectively make `wait()` and/or `waitAsync()` redundant? Have you filed a PR for the WASM library to use `waitAsync()`?
